- repository: autowarefoundation/autoware
  files:
    - source: .github/dependabot.yaml
    - source: .github/workflows/pre-commit.yaml
    - source: .github/workflows/pre-commit-optional.yaml
    - source: .github/workflows/semantic-pull-request.yaml
    - source: .github/workflows/spell-check-differential.yaml
    - source: .github/workflows/sync-files.yaml
    - source: .clang-format
    - source: .markdown-link-check.json
    - source: .markdownlint.yaml
    - source: .pre-commit-config-optional.yaml
    - source: .prettierignore
    - source: .prettierrc.yaml
    - source: .yamllint.yaml
    - source: CPPLINT.cfg
    - source: setup.cfg

- repository: autowarefoundation/autoware_common
  files:
    - source: .github/workflows/build-and-test.yaml
    - source: .github/workflows/build-and-test-differential.yaml
    - source: .github/workflows/cancel-previous-workflows.yaml

- repository: autowarefoundation/autoware.universe
  files:
    - source: .github/workflows/cppcheck-all.yaml
    - source: .github/workflows/cppcheck-differential.yaml
    - source: .cppcheck_suppressions
