- repository: autowarefoundation/sync-file-templates
  source-dir: sources
  files:
    - source: .github/dependabot.yaml
    - source: .github/pull_request_template.md
    - source: .github/workflows/backport.yaml
    - source: .github/workflows/build-and-test.yaml
    - source: .github/workflows/build-and-test-differential.yaml
    - source: .github/workflows/pre-commit.yaml
    - source: .github/workflows/pre-commit-optional.yaml
    - source: .github/workflows/semantic-pull-request.yaml
    - source: .github/workflows/spell-check-daily.yaml
    - source: .github/workflows/spell-check-differential.yaml
    - source: .github/workflows/sync-files.yaml
    - source: .clang-format
    - source: .clang-tidy
    - source: .markdownlint.yaml
    - source: .pre-commit-config.yaml
    - source: .pre-commit-config-optional.yaml
    - source: .prettierignore
    - source: .prettierrc.yaml
    - source: .yamllint.yaml
    - source: CPPLINT.cfg
    - source: setup.cfg

- repository: autowarefoundation/autoware_universe
  files:
    - source: .github/workflows/cppcheck-weekly.yaml
    - source: .github/workflows/cppcheck-differential.yaml
    - source: .github/cppcheck-problem-matcher.json
    - source: .cppcheck_suppressions
